modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "https://github.com/starfish-studios/Building-But-Better/blob/main/LICENSE"

[[mods]]
modId = "bbb"
version = "${version}"
displayName = "Building But Better: Reloaded"
authors = "Starfish Studios"
description = '''
A mod focused on adding new building blocks with customizability and interactions!\n§c§l§u§o! Pre-releases WILL be buggy ! §cPlease report any issues on our GitHub or Discord.\n§9§l§uCHANGELOG (2.0pre1)§7\n- Added Stone Frames and fixed Frames crashing when connecting to non-solid blocks.\n- Added Balustrades\n- Added Lattices\n- Added native EveryCompat support.\n- There's a config now !!\n- Urns can now be interacted with Dirt -- when they are filled in this way, plants can be placed atop them. Use a Shovel to remove the Dirt.
'''
#logoFile = ""

[[dependencies.building_but_better]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.building_but_better]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.building_but_better]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bbb.mixins.json"